version: "3.6"
services:
    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
        ports:
            - 9300:9300
            - 9200:9200
        environment:
            - "discovery.type=single-node"
        volumes:
            - ./elasticdata:/usr/share/elasticsearch/data

    nginx:
        build:
            context: .docker/nginx
            dockerfile: Dockerfile
        volumes:
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/docs.dangit
        ports:
            - 80:80
            - 443:443
        links:
            - php:php

    php:
        build:
            context: .docker/php
            dockerfile: Dockerfile
        image: docsdangit-php:latest
        volumes:
            - .:/var/www/docs.dangit
        ports:
            - 9000:9000
        links:
            - elastic:elastic

